### ISSUE TITLE
consider .gitattributes & .editorconfig

### ISSUE THREAD

**Issue by watchmanpluginteam** [Ignition-IT/Watchman-Plugins#3]
Nice work on having plugins for more than one platform!

We've found that having a gitattributes file in a repo can help prevent weird issues in the working copy:

https://git-scm.com/docs/gitattributes

**Comment by ella-ignition** [comment]
Thanks for the recommendation! I'm quite new to using GitHub and don't know best practices yet 😅 I've added a .gitattributes file with some entries for .plugin and .plist files, let me know if there's any changes you think I should make.

Thanks!
